#!/usr/bin/env sh
#
# update-github v1.0.4
# aggiorna il deposito locale con quello remoto
#
#    Copyright (C) <2000 - 2020>  <Luca Cappelletti>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

[ -z $1 ] && commento=""

# i parametri commentati sono stati inseriti nell'hook git pre-commit
git config --global user.name "BarbaraGiambi"
git config --global user.email barbara.giambi.scuola@gmail.com

commento=$1
versione=$2

# lista tags
git tag

# update-github ha senso con un repo centralizzato master github
# implica che il sync prima del push è doveroso
echo "Allineo il repo locale al remoto prima di spingere i cambiemti locali"
git pull
wait

# annota tags
echo "Aggiungo i cambiamenti al database locale"
git add -A .

echo "Eseguo la finalizzazione dei cambiamenti in locale"
EPOCA_UNIX=$(date +%N)
COMMENTO="["$EPOCA_UNIX"] "$commento
VERSIONE="v"$versione

echo "Commento transazione: "$COMMENTO
git commit -a -m "$COMMENTO"
wait

echo "Invio i cambiamenti locali al deposito remoto..."
git push origin master
wait

[ -z $2 ] || { echo "Versione: "$VERSIONE; git tag -a $VERSIONE -m "$COMMENTO"; git push origin --tags; git tag; }
wait

[ -z $2 ] && git tag

echo "ok"
